name: Config Update

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ensure rule folder exists
        run: |
          if [ ! -d "rule" ]; then
            mkdir -p rule
            echo "Created rule folder."
          else
            echo "rule folder exists."
          fi

      - name: Ensure adguard folder exists
        run: |
          if [ ! -d "adguard" ]; then
            mkdir -p adguard
            echo "Created adguard folder."
          else
            echo "adguard folder exists."
          fi

      - name: "Setup sing-box"
        env:
          SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.10.0-alpha.27/sing-box_1.10.0-alpha.27_linux_amd64.deb"
        run: |
          set -Eeuo pipefail
          wget -O sing-box.deb $SING_BOX_DEB_URL
          sudo dpkg -i sing-box.deb

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pyyaml

      - name: Download and convert adguard filter
        run: |
          wget -O adguard/filter.txt https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
          sing-box rule-set convert --type adguard --output adguard/filter.srs adguard/filter.txt

      - name: Run script
        run: python ../main.py
        working-directory: ./rule/

      - name: Commit and push config.json
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add ./rule/*.json 2>/dev/null || true
          git add ./rule/*.srs 2>/dev/null || true
          git add ./rule/*.txt 2>/dev/null || true
          git add ./adguard/*.srs 2>/dev/null || true

          # 检查是否有文件被修改
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update rules"
            git push
          fi
